image: registry.gitlab.com/pages/hugo:latest

stages:
  - build
  - deploy

variables:
  HUGO_OUTPUT_DIR: "public"

cache:
  paths:
    - .hugo_cache/

default:
  tags:
    - docker

before_script:
  - apk add --no-cache openssh-client git
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY"
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  # - git submodule update --init --recursive
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "Z"
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo "A"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


build:
  stage: build
  script:
    - echo "B"
    - set -x
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - echo "C"
    - hugo
  artifacts:
    paths:
      - ${HUGO_OUTPUT_DIR}
  only:
    - main

pages:
  stage: deploy
  script:
    - echo "Deployment step"
  artifacts:
    paths:
      - public
  only:
    - main
